server:
  port: 8060

spring:
  application:
    name: census31-fwmt-csvservice
  security:
    user:
      name: "user"
      password: "password"

management:
  # Place /info and /health in the root
  endpoints.web.base-path: ''
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info,env,refresh}
  endpoint:
    health:
      show-details: always
    env:
      enabled: ${APP_TESTING:false}
      post:
        enabled: ${APP_TESTING:false}
    refresh:
      enabled: ${APP_TESTING:false}

logging:
  profile: DEV
  level:
    root: WARN
    uk.gov.ons.census.fwmt: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    org.apache.commons.dbcp2: INFO
    org.springframework: INFO

gcpBucket:
   celocation: "file://${home}/acceptance/data/ceTestCSV.csv"
   ccslocation: "file://${home}/acceptance/data/ccsTestCSV.csv"
   addresschecklocation: "file://${home}/acceptance/data/AC.csv"
   postcodelookuplocation: "file://${home}/acceptance/data/addressLookup.csv"
   directory: "file://${home}/acceptance/data/"

app:
  testing: false
  retry:
    initialInterval: 5000
    multiplier: 3.0
    maxInterval: 45000
  messaging:
    provider: pubsub
    destinations:
      gatewayActions: "Gateway.Actions.Exchange"

---
spring:
  config:
    activate:
      on-property:
        name: app.messaging.provider
        having-value: pubsub
  cloud:
    gcp:
      project-id: fwmt-local
      credentials:
        enabled: true
      pubsub:
        enabled: true
      storage:
        enabled: false
